### PR TITLE
v1.2

### PR DESCRIPTION
**Pull request by ethanmad**
AppCompat, new icon, sdk version 22, bug fixes, more structure, and a prettier iHW.

### CODE REVIEW

**Comment by ethanmad** [comment]
For future reference (I know you know the answers by now @jburns20):
<br>
> Where'd you get this new icon? Who is "REM Designs"?

The icon is a part of what is currently called "[Cake Pop Icons](https://plus.google.com/communities/101391538081027754644)" by Srini Kumar.
<br>
> You removed the dark_red color from the colors file but view_period.xml, styles.xml, and PeriodView.java still depend on it

&

> You removed the lighter_red drawable from the colors file but cab_background.xml still depends on it

These color references were fixed in 572d1d3 and d5aafd5. The names of the colors were changed to `primary`, `primaryDark`, and `accent`.

**Comment by ethanmad** [comment]
Nearly ready for release/beta testing. I haven't experienced any crashes in the latest version. The only issue remaining as far as I know is that edit courses doesn't quite work. I can add courses, but the list of courses loads endlessly and doesn't ever show up. @jburns20 can you take a look?

**Comment by ethanmad** [comment]
@jburns20 I see what NormalCoursesActivity is supposed to load-- a list of the courses. With the current implementation, I think it is trying to load this list (changed in latest commit; turns out the content view did need to switch), but it loads forever. I'm going to blame something after [this line](https://github.com/HWComputerScience/iHW-Android/commit/dbf9e42a2277b241f35b21e518a9289446afb239#diff-1df617a860bb06502f1829831b9d9abcR80) in CoursesActivity (my changes making it into a fragment probably broke something), but I'm not sure.

**Comment by ethanmad** [comment]
Closing this until it's ready.

**Comment by jburns20** [comment]
Should be fixed now

**Comment by ethanmad** [comment]
@ile123ile f544b11 fixed the icons that we discussed; no need to worry about that now. 1.2 is almost ready, so get your names in there!

**Comment by ethanmad** [comment]
v1.2.0 should be finished now. My last series of commits [prepared the app for Android 6.0 Marshmallow][0], [improved the edit course screen][1] (ordinals were messing up the UI on my device and added unnecessary visual complexity), and [removed multiselection in the courses list][2] (broken and pointless in my opinion).

Check it over @jburns20 @ile123ile? Specifically the edit course area of the app. The year has to be set to 2014-15 (server-side switch has to be flipped?).

If you two sign off, I'll take screenshots and upload it to Google Play. Still some null pointers that should be addressed, but as far as I know they're not too bad and can be fixed in v1.2.1. In that same release or in a followup, small UI enhancements could be made, too.

Anyway, I think v1.2.0 is ready and we should ship rather than delaying any longer (that's on me).

[0]: https://github.com/HWComputerScience/iHW-Android/commit/cf49c1259d6abeb271c785eb19308b067f8c0c43
[1]: https://github.com/HWComputerScience/iHW-Android/commit/cb86a9bd09dd710cc3533380ee9ad86c8cbd1aac
[2]: https://github.com/HWComputerScience/iHW-Android/commit/acff68a04b233600e53f110929e08d3337ce119b

**Comment by ile123ile** [comment]
Looks great, I'll get started on v1.2.1 and those null pointers next week.

**Comment by ethanmad** [comment]
At 8pm tonight, I'll make the HEAD of this branch into a beta on the Play Store. If there any urgent issues that are not addressed yet, please say so now.

@ile123ile Send me your schedule and I'll use it for the Play Store images.

**Comment by ile123ile** [comment]
Here's my schedule, I don't think there are any issues.

**Comment by ethanmad** [comment]
@ile123ile I don't think attachments work. List the courses and periods? Otherwise I can just make one up.

**Comment by ile123ile** [comment]
I was in the middle of editing the comment when you replied

**Comment by ile123ile** [comment]
did you get it?

**Comment by ethanmad** [comment]
iHW v1.2.1 released to the Play Store as a beta (join [here](https://plus.google.com/communities/105782646891156329465)) and to our [GitHub release page](https://github.com/HWComputerScience/iHW-Android/releases/tag/1.2.1). @ile123ile  Please see if you can recruit friends to use v1.2.1 rather than the stable version for the next week and have them report issues (to you, GItHub, Google+, me, whatever).

I've updated the Play Store listing with new screenshots, a screencast, and the new app icon. Please complain to me if something is wrong with the new listing. The Play Store will take several hours to update--it should be good by morning.

Also, since the current release is v1.2.1, milestone 1.2.1 is now [1.2.2](https://github.com/HWComputerScience/iHW-Android/milestones/1.2.2).

If all goes well, we can move v1.2.1 to production. Unless anything is broken and needs fixing, let's revisit in a week to merge this.

**Comment by jononon** [comment]
Do you want me to share the beta with people for feedback?

**Comment by ethanmad** [comment]
@jononon Go for it. I'm not expecting this release to be perfect; I only want to ensure there are no regressions. The next release will focus on increasing stability.

**Comment by jononon** [comment]
Perfect. thanks!

**Comment by ethanmad** [comment]
It's now been slightly over a week. What's the verdict on stability for version 1.2.1? Ready for production or not yet?

**Comment by ile123ile** [comment]
Seems pretty stable, I have noticed that both the day of the week and the jump to day features are gone, is that intentional? Sometimes crashes rarely, but hard to repro and not very often.

**Comment by ethanmad** [comment]
@ile123ile Jump to day is gone on < 5.1 because it's not supported for some reason (possible solution would be to use the old datepicker on older versions of Android - [this](https://github.com/HWComputerScience/iHW-Android/blob/v1.2/app/src/main/java/com/ihwapp/android/ScheduleActivity.java#L211) is the line disabling the new datepicker on old versions).

Day of week should be there as of 3950ea32aa930677dc2efe1f8af1491a47994938. Are you maybe on an older version? Try the latest commit, cadd350876e48559a4bc57086c47577941b68f0d.

**Comment by ile123ile** [comment]
Sorry I was on an old version. I think it's probably good to go in that case, maybe we can add support for the datepicker on older versions in 1.2.2, but I don't think anyone used it anyways.

**Comment by ethanmad** [comment]
Sorry to change version numbers again, but the version I just released is 1.2.2 and what was 1.2.2 is now 1.2.3. 1.2.2 includes a minor change to the about page. Srini Kumar (who designed the current icon) told me he wants to redo it now that he has more experience, so we can expect soon enough.

Anyway, I released 1.2.2 on GitHub and moved it to production on the Play Store. Everyone should have the option to update before school starts on Monday.

Please watch for complaints in the coming days; we can roll back to 1.1.4 if necessary.

**Pull request merged**
